/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenjaminRouteImport } from './routes/benjamin'
import { Route as BoekRouteImport } from './routes/boek'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ModelRouteImport } from './routes/model'
import { Route as ScholingenRouteImport } from './routes/scholingen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenjaminRoute = BenjaminRouteImport.update({
  id: '/benjamin',
  path: '/benjamin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekRoute = BoekRouteImport.update({
  id: '/boek',
  path: '/boek',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholingenRoute = ScholingenRouteImport.update({
  id: '/scholingen',
  path: '/scholingen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benjamin': typeof BenjaminRoute
  '/boek': typeof BoekRoute
  '/contact': typeof ContactRoute
  '/model': typeof ModelRoute
  '/scholingen': typeof ScholingenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benjamin': typeof BenjaminRoute
  '/boek': typeof BoekRoute
  '/contact': typeof ContactRoute
  '/model': typeof ModelRoute
  '/scholingen': typeof ScholingenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benjamin': typeof BenjaminRoute
  '/boek': typeof BoekRoute
  '/contact': typeof ContactRoute
  '/model': typeof ModelRoute
  '/scholingen': typeof ScholingenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/benjamin' | '/boek' | '/contact' | '/model' | '/scholingen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benjamin' | '/boek' | '/contact' | '/model' | '/scholingen'
  id:
    | '__root__'
    | '/'
    | '/benjamin'
    | '/boek'
    | '/contact'
    | '/model'
    | '/scholingen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenjaminRoute: typeof BenjaminRoute
  BoekRoute: typeof BoekRoute
  ContactRoute: typeof ContactRoute
  ModelRoute: typeof ModelRoute
  ScholingenRoute: typeof ScholingenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benjamin': {
      id: '/benjamin'
      path: '/benjamin'
      fullPath: '/benjamin'
      preLoaderRoute: typeof BenjaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boek': {
      id: '/boek'
      path: '/boek'
      fullPath: '/boek'
      preLoaderRoute: typeof BoekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholingen': {
      id: '/scholingen'
      path: '/scholingen'
      fullPath: '/scholingen'
      preLoaderRoute: typeof ScholingenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenjaminRoute: BenjaminRoute,
  BoekRoute: BoekRoute,
  ContactRoute: ContactRoute,
  ModelRoute: ModelRoute,
  ScholingenRoute: ScholingenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
